### PR TITLE
Add Phoenix.phar support #2

### PR DESCRIPTION
**Pull request by NoHaxJustTryHqrd**
These ones have better syntax.

### CODE REVIEW

**Comment by dktapps** [comment]
There are syntax errors, and a considerable amount of changes for this one thing. I was expecting you to amend your previous PR, not spam another one.

**Comment by NoHaxJustTryHqrd** [comment]
I will amend my other one but whats weird is that the syntax was perfect when i edited the file on my device but when i uploaded to github thinks went crazy

**Comment by dktapps** [comment]
Do not use the web editor or file upload. Learn to use Git.

**Comment by daniktheboss** [comment]
👍 git is the way to go

**Pull request closed without merging**
