### PR TITLE
Change file names to Phoenix

### PR DESCRIPTION
**Pull request by TheAppleGamer**
This changes most installer names to Phoenix.

### CODE REVIEW

**Comment by Sandertv** [comment]
I'm not sure if @dktapps wants this... In my opinion too we should try to keep most pocketmine related stuff PocketMine for when it maybe, a lot of time later gets merged into the master branch.

**Comment by TheAppleGamer** [comment]
Alright. I'll close it, wasn't too sure if he wanted it to be renamed to it either.

**Comment by Sandertv** [comment]
We'll see if he does :)

**Comment by TheAppleGamer** [comment]
He'll notice it was closed. We'll just wait and see :)

**Comment by dktapps** [comment]
Of course I'll notice, I'm watching the repo. :P

**Comment by TheAppleGamer** [comment]
Does this PR have any use?

**Comment by dktapps** [comment]
This is not quite what I'm looking for. Thanks anyway. A better approach would be to use parameters.

**Comment by TheAppleGamer** [comment]
Okay. I was going to work on the AutoUpdater. Do you have any use for that?

**Comment by dktapps** [comment]
Not yet. This repository is going to move, so don't get too excited

**Pull request closed without merging**
