### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Dog2puppy**

### CODE REVIEW

**Comment by dktapps** [comment]
This is unnecessary currently. Thanks anyway, we'll add this when it is necessary.

**Comment by Dog2puppy** [comment]
And is the ISSUE_TEMPLATE.md needed when there arent any issues??

**Comment by dktapps** [comment]
That was already present from PocketMine, please review the commit history.

**Comment by Dog2puppy** [comment]
Oh.

**Comment by SOF3** [comment]
@Dog2puppy I think the issue template is more needed when there aren't issues than when there are issues.

**Pull request closed without merging**
